[workspace]
resolver = "2"

members = [
  "crates/lcsfe-algorithm",
  "crates/lcsfe-pg",
  "crates/lcsfe-common",
  "crates/lcsfe-cli",
  "crates/lcsfe-mu-ald"
]

[profile.release]
lto = "fat"
codegen-units = 1
