[workspace]
resolver = "2"

members = [
  "crates/sem-sfe-algorithm",
  "crates/sem-sfe-pg",
  "crates/sem-sfe-common",
  "crates/sem-sfe-cli",
  "crates/sem-sfe-mu-ald"
]

[profile.release]
lto = "fat"
codegen-units = 1
