[package]
name = "sem-lmc-pg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sem-lmc-common = { path = "../sem-lmc-common" }
sem-lmc-algorithm = { path = "../sem-lmc-algorithm" }
