from: markdown

to: pdf

input-files:
  - installation_and_usage.md
  - project_structure.md
  - mu_ald_module.md
  - examples.md
  - pg_module.md
  - comparison_and_benchmarks.md

pdf-engine: pdflatex

output-file: ${.}/report.pdf

metadata-file: ${.}/metadata.yaml

strip-comments: true

number-sections: true
