[package]
name = "sem-lmc-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sem-lmc-algorithm = { path = "../sem-lmc-algorithm" }